version: '3.9'

services:
  container1:
    build: ./container1
    container_name: container1
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./data:/data
    environment:
      - APP_NAME=flaskapp1

  container2:
    build: ./container2
    container_name: container2
    restart: always

    ports:
      - 6000:6000
    volumes:
      - ./data:/data
    environment:
      - APP_NAME=flaskapp2
